modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT License"
issueTrackerURL = "https://github.com/brnbrd/CollectorsReap/issues"

[[mods]]
modId = "collectorsreap"
version = "${file.jarVersion}"
displayName = "Collector's Reap"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/collectors-reap"
updateJSONURL = "https://raw.githubusercontent.com/brnbrd/CollectorsReap/1.20.1/update.json"
logoFile = "collectorsreap.png"
logoBlur = false
credits = "reNIK03, brdbrn, vectorwing"
authors = "reNIK03, brdbrn"
description = "Farmer's Delight addon with foods scavenged from the wild."
itemIcon = "collectorsreap:lime_slice"
configBackground = "collectorsreap:textures/block/pomegranate_ice_cream_block.png"

[[dependencies.collectorsreap]]
	modId = "forge"
	mandatory = true
	versionRange = "[47,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.collectorsreap]]
	modId = "farmersdelight"
	mandatory = true
	versionRange = "[1.20.1-1.2.3,)"
	ordering = "AFTER"
	side = "BOTH"

[[dependencies.collectorsreap]]
	modId = "nethersdelight"
	mandatory = false
	versionRange = "[0,)"
	ordering = "AFTER"
	side = "BOTH"

[[dependencies.collectorsreap]]
	modId = "mynethersdelight"
	mandatory = false
	versionRange = "[1.20.1-1.0,)"
	ordering = "AFTER"
	side = "BOTH"

[[dependencies.collectorsreap]]
	modId = "neapolitan"
	mandatory = false
	versionRange = "[0,)"
	ordering = "AFTER"
	side = "BOTH"

[[dependencies.collectorsreap]]
	modId = "farmersrespite"
	mandatory = false
	versionRange = "[1.20.1-2.1,)"
	ordering = "AFTER"
	side = "BOTH"

[[dependencies.collectorsreap]]
	modId = "botanypots"
	mandatory = false
	versionRange = "[13,)"
	ordering = "AFTER"
	side = "BOTH"